import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  SCHEMA, buildTaskDossier, executorClaimsIssue, extractTaskTopology, groupFindings,
  requiredGateChecks, reviewContractIssue, reviewNeedsChallenger, taskDeliveryDiff, taskKey,
} from '../caw.mjs'

const spec = `---
id: 001
task_key: profile-language-authority
title: Dossier
---

## Surfaces
- \`settings-language\` — The selected language and its mounted consumers

## State machines
- \`settings-language\`: states \`english\`, \`ukrainian\`
  - \`english\` -- select Ukrainian --> \`ukrainian\`

## Done when
- The mounted settings consumer updates.

## Required gate checks
- \`settings-language-ui\` — proves the mounted consumer switches
`

test('task identity and required gate evidence do not depend on queue numbering', () => {
  assert.equal(taskKey('.caw-tasks/018_any-name.md', spec), 'profile-language-authority')
  assert.deepEqual(requiredGateChecks('.caw-tasks/018_any-name.md', spec), ['settings-language-ui'])
})

test('risk challenger policy escalates only concrete risk signals', () => {
  const f = { review_challenger_policy: 'risk', review_challenger_passes: 1,
    review_challenger_file_threshold: 8 }
  assert.equal(reviewNeedsChallenger(f, ['src/plain.js']), false)
  assert.equal(reviewNeedsChallenger(f, ['src/auth/session.js']), true)
  assert.equal(reviewNeedsChallenger(f, ['src/plain.js'], [], { broken: [{ id: 'x' }] }), true)
})

test('task topology gives criteria, surfaces and transitions stable ids', () => {
  const first = extractTaskTopology(spec)
  const second = extractTaskTopology(spec)
  assert.deepEqual(first, second)
  assert.deepEqual(first.criteria.map((row) => row.id), ['done-when-1'])
  assert.deepEqual(first.surfaces, [{
    id: 'settings-language', responsibility: 'The selected language and its mounted consumers',
  }])
  assert.equal(first.transitions.length, 1)
  assert.match(first.transitions[0].id, /^transition-[0-9a-f]{12}$/)
  assert.equal(first.transitions[0].surface, 'settings-language')
})

test('task dossier bounds every section and records every truncation', () => {
  const huge = 'é'.repeat(100_000)
  const dossier = buildTaskDossier({
    spec: `${spec}\n${huge}`,
    profile: huge,
    files: ['src/a.js'],
    diff: huge,
    open: [{ id: 'r1.1', evidence: huge }],
    gateEvidence: { state: 'green', output: huge },
    executorClaims: [{ summary: huge }],
    acceptanceCases: [{ observable: huge }],
  })
  assert.ok(Buffer.byteLength(dossier.text) <= 192 * 1024)
  assert.equal(dossier.meta.total_included_bytes, Buffer.byteLength(dossier.text))
  assert.equal(dossier.meta.version, 1)
  assert.equal(dossier.meta.sections.some((section) => section.truncated), true)
  assert.equal(dossier.meta.sections.every((section) =>
    section.included_bytes <= section.source_bytes), true)
  assert.match(dossier.text, /Task dossier generated by CAW/)
  assert.match(dossier.text, /repository reads remain available/)
})

test('task delivery diff includes tracked edits and new untracked files', (t) => {
  const root = mkdtempSync(join(tmpdir(), 'caw-task-diff-test-'))
  t.after(() => rmSync(root, { recursive: true, force: true }))
  execFileSync('git', ['init', '-q'], { cwd: root })
  execFileSync('git', ['config', 'user.email', 'fixture@example.invalid'], { cwd: root })
  execFileSync('git', ['config', 'user.name', 'fixture'], { cwd: root })
  writeFileSync(join(root, 'tracked.txt'), 'before\n')
  execFileSync('git', ['add', 'tracked.txt'], { cwd: root })
  execFileSync('git', ['commit', '-q', '-m', 'fixture'], { cwd: root })
  writeFileSync(join(root, 'tracked.txt'), 'after\n')
  mkdirSync(join(root, 'src'))
  writeFileSync(join(root, 'src', 'new.txt'), 'new delivery\n')

  const diff = taskDeliveryDiff(root)

  assert.match(diff, /tracked\.txt/)
  assert.match(diff, /\+after/)
  assert.match(diff, /src\/new\.txt/)
  assert.match(diff, /\+new delivery/)
})

test('executor claims are untrusted but must link to the known contract', () => {
  assert.ok(SCHEMA.delivery.required.includes('claims'))
  const claim = {
    id: 'settings-ui-test',
    criterion_ids: ['done-when-1'],
    acceptance_case_ids: [],
    command: 'scripts/gate_fast.sh --ui settings',
    selector: 'SettingsLanguageTests/testSwitch',
    result: 'passed',
    summary: 'The settings language scenario passed.',
    artifact_refs: ['settings-ui.xcresult'],
  }
  assert.equal(executorClaimsIssue([claim], extractTaskTopology(spec).criteria), null)
  assert.match(executorClaimsIssue([{ ...claim, criterion_ids: ['done-when-9'] }],
    extractTaskTopology(spec).criteria), /unknown criterion/)
  assert.match(executorClaimsIssue([{ ...claim, criterion_ids: [], command: '' }],
    extractTaskTopology(spec).criteria), /without a command/)
  assert.match(executorClaimsIssue([{ ...claim, acceptance_case_ids: ['ui-case'] }],
    extractTaskTopology(spec).criteria, [{ id: 'ui-case', selector: 'another.selector' }]),
  /wrong selector/)
})

test('finding work packages group exact root-cause keys and preserve every member', () => {
  const common = {
    criterion_ids: ['done-when-1'],
    surface_ids: ['settings-language'],
    transition_ids: [],
    state: 'open',
  }
  const findings = [
    { ...common, id: 'r1.1', property_key: 'locale.propagation', evidence: 'first pass' },
    { ...common, id: 'r1.2', property_key: 'locale.propagation', evidence: 'challenger pass' },
    { ...common, id: 'r1.3', property_key: 'retry.enabled-state', evidence: 'same screen' },
  ]

  const groups = groupFindings(findings)

  assert.equal(groups.length, 2)
  assert.deepEqual(groups[0].members.map((row) => row.id), ['r1.1', 'r1.2'])
  assert.deepEqual(groups[0].members.map((row) => row.evidence), ['first pass', 'challenger pass'])
  assert.deepEqual(groups[1].members.map((row) => row.id), ['r1.3'])
})

test('review evidence distinguishes engine receipts from untrusted claims', () => {
  const topology = extractTaskTopology(spec)
  const base = {
    criteria: [{
      id: 'done-when-1', state: 'met', evidence: 'executor reported success',
      evidence_refs: ['executor-claim:claim-1'],
    }],
    carried: [], broken: [], uncovered: [], weak: [], noted: [],
  }
  const context = {
    ...topology,
    receipt: {
      receipt_id: 'receipt-1',
      manifest: { checks: [{ id: 'check-1' }] },
      artifacts: [],
    },
    claims: [{ id: 'claim-1' }],
  }

  assert.match(reviewContractIssue(base, context), /relies only on untrusted executor claims/)
  assert.equal(reviewContractIssue({
    ...base,
    criteria: [{
      ...base.criteria[0],
      evidence_refs: ['gate-receipt:receipt-1', 'executor-claim:claim-1'],
    }],
  }, context), null)
  assert.match(reviewContractIssue({
    ...base,
    criteria: [{
      ...base.criteria[0],
      evidence_refs: ['repository:src/./settings.js'],
    }],
  }, context), /unsafe repository evidence reference/)
})
